name : EBAC ci

on : 
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set Node env
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependências
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          install-command: npm install
          browser: chrome

      - name: Gerar relatório
        run: npm run report
        
      - name: Mesclar relatórios
        run: npm run merge

      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          publish_dir: ./mochawesome-report
