name : EBAC ci

on : 
  push:
    branches: [main]
  
 # acionar maunal
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Node env
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cypress run
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          install-command: npm install
          browser: chrome

      - name: Generate report
        run: npx report # Executa o comando para gerar o relatório

      - name: Merge reports
        run: npx merge # Executa o comando para mesclar os relatórios

      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          publish_dir: ./mochawesome-report
